{
    'name': 'Custom DJI Administration',
    'summary': """Administration settings for DJI""",
    'version': '14.0.1.0.0',
    'description': """Administration settings for DJI""",
    'author': 'Dani Domínguez',
    'company': 'Xtendoo',
    'website': 'https://xtendoo.es',
    'category': 'Admin Tools',
    'depends': [
        'base',
        'sale',
        'purchase',
        'product',
        'website',
        'crm',
        'sale_margin',
        'account',
        'stock',
        'website_sale',
        'account_invoice_margin',
        'account_banking_mandate',
        'edi_account_oca',
        'account_payment_return',
        'account_payment_return_import',
        'account_asset_management',
        'sale_commission',
        'sale_order_line_margin_percent',
    ],
    'license': 'AGPL-3',
    'data': [
        'security/security_group.xml',
        'security/ir.model.access.csv',
        'views/sale_order_views.xml',
        'views/product_views.xml',
        'views/account_move_views.xml',
    ],
    'installable': True,
    'auto_install': True,
}

